# Generated by Django 5.0 on 2024-01-19 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0015_alter_productimage_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='state',
            new_name='region',
        ),
    ]
