# Generated by Django 5.0 on 2024-01-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0016_rename_state_order_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pincode',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
