# Generated by Django 5.0 on 2024-01-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0017_alter_order_country_alter_order_payment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_mark_as_received',
            field=models.BooleanField(default=False),
        ),
    ]
