# Generated by Django 5.0 on 2024-01-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0019_alter_order_country_alter_order_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Out for Shipping', 'Out for Shipping'), ('Completed', 'Completed')], default='Processing', max_length=50),
        ),
    ]
