# Generated by Django 5.0 on 2024-01-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0020_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.CharField(choices=[('Ashanti Region', 'Ashanti Region'), ('Brong-Ahafo Region', 'Brong-Ahafo Region'), ('Central Region', 'Central Region'), ('Eastern Region', 'Eastern Region'), ('Greater Accra Region', 'Greater Accra Region'), ('Northern Region', 'Northern Region'), ('Oti Region', 'Oti Region'), ('Upper East Region', 'Upper East Region'), ('Upper West Region', 'Upper West Region'), ('Volta Region', 'Volta Region'), ('Western Region', 'Western Region'), ('Western North Region', 'Western North Region')], max_length=150),
        ),
    ]
