# Generated by Django 4.2.4 on 2024-05-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0024_agentvodabundleprice_superagentvodabundleprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingTrackingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=150, null=True)),
                ('goods', models.TextField(blank=True, null=True)),
                ('shipping_fee', models.FloatField(blank=True, null=True)),
                ('goods_amount', models.FloatField(blank=True, null=True)),
                ('recent_change_date', models.DateTimeField(auto_now_add=True)),
                ('pickup_location', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
