# Generated by Django 4.2.4 on 2024-05-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0025_shippingtrackinginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preorder_arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='preorder_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='preorder_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shippingtrackinginfo',
            name='shipment_status',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
