# Generated by Django 4.2.4 on 2024-05-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0027_statusname_shipmentstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentstatus',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
