# Generated by Django 4.2.4 on 2024-07-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0029_package_shippingorder_tracking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='status',
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='status',
            field=models.CharField(default='hi', max_length=50),
            preserve_default=False,
        ),
    ]
