# Generated by Django 4.2.4 on 2024-07-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0030_remove_package_status_shippingorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='cbm',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='package_tracking_number',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='owner_name',
            field=models.CharField(default='hu', max_length=250),
            preserve_default=False,
        ),
    ]
