# Generated by Django 4.2.4 on 2024-07-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0032_alter_package_cbm_alter_package_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingorder',
            name='phone_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
