# Generated by Django 4.2.4 on 2024-07-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0033_shippingorder_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingorder',
            name='order_number',
            field=models.CharField(max_length=20),
        ),
    ]
