# Generated by Django 4.2.4 on 2024-07-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0035_shippingorder_recent_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unique_shipping_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
