# Generated by Django 4.2.4 on 2024-10-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0038_announcement_alter_package_cbm_alter_package_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='ishare_channel',
            field=models.CharField(choices=[('Geosams', 'Geosams'), ('Nexus', 'Nexus')], default='Geosams', max_length=250),
        ),
    ]
